apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/gpu-operator/application.yaml
  - apps/monitoring/crds-application.yaml
  - apps/monitoring/application.yaml
  - apps/logging/application.yaml
